[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "https://www.unpkg.com"

[[redirects]]
  from = "/3.4/*"
  to = "https://release-3-4--lynx-doc.netlify.app/:splat"
  status = 200


[[redirects]]
  from = "/3.5/*"
  to = "/:splat"
  status = 301