/**
 * Generates a TypeDoc-compatible entry point for @lynx-js/type-element-api.
 *
 * The original package uses `declare global { ... }` to define global functions,
 * which TypeDoc does not document (it only processes module-level exports).
 * This script extracts the global function declarations and re-declares them
 * as module-level exports so TypeDoc can generate documentation for them.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_FILE = path.resolve(__dirname, 'entries/element-api.d.ts');

export function generateElementApiEntry() {
  if (!process.env.LYNX_REPO) {
    throw new Error(
      'LYNX_REPO must point to a Lynx checkout when generating Element API docs.',
    );
  }

  const sourceFile = path.resolve(
    process.env.LYNX_REPO,
    'lynx/js_libraries/type-element-api/types/element-api.d.ts',
  );

  if (!fs.existsSync(sourceFile)) {
    throw new Error(
      `Could not find the Element API declaration at ${sourceFile}.`,
    );
  }

  const source = fs.readFileSync(sourceFile, 'utf-8');

  const sourceFileNode = ts.createSourceFile(
    sourceFile,
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const globalDeclaration = sourceFileNode.statements.find(
    (statement): statement is ts.ModuleDeclaration =>
      ts.isModuleDeclaration(statement) &&
      ts.isIdentifier(statement.name) &&
      statement.name.text === 'global',
  );
  if (!globalDeclaration?.body || !ts.isModuleBlock(globalDeclaration.body)) {
    throw new Error(
      'Could not find `declare global` block in element-api.d.ts',
    );
  }

  const globalBlock = source.slice(
    globalDeclaration.body.getStart(sourceFileNode) + 1,
    globalDeclaration.body.getEnd() - 1,
  );

  // Convert `function __Foo(...)` declarations to `export declare function __Foo(...)`
  const exportedFunctions = globalBlock
    .split('\n')
    .map((line) => {
      // Match function declarations (with optional leading whitespace)
      const funcMatch = line.match(/^(\s*)function\s+/);
      if (funcMatch) {
        const indent = funcMatch[1];
        return line.replace(
          /^(\s*)function\s+/,
          `${indent}export declare function `,
        );
      }
      return line;
    })
    .join('\n');

  // Extract the module-level exports (everything before `declare global`)
  // Strip any leading block comments (e.g. copyright headers) to prevent
  // TypeDoc from treating them as module documentation.
  const moduleExports =
    `${source.slice(0, globalDeclaration.getFullStart())}${source.slice(globalDeclaration.getEnd())}`
      .trim()
      .replace(/^(?:\/\/[^\n]*\n)+\s*/, '')
      .trim();

  // Use a non-JSDoc comment (// style) to avoid TypeDoc treating it as module documentation
  const output = `// THIS FILE IS AUTO-GENERATED by scripts/typedoc/generate-element-api-entry.ts
// DO NOT EDIT MANUALLY.
//
// It re-exports the global function declarations from @lynx-js/type-element-api
// as module-level exports so that TypeDoc can document them.

${moduleExports}

${exportedFunctions}
`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`Generated TypeDoc entry point: ${OUTPUT_FILE}`);
}

// Allow direct execution: `npx tsx scripts/typedoc/generate-element-api-entry.ts`
const isDirectExecution =
  process.argv[1] &&
  (process.argv[1].endsWith('generate-element-api-entry.ts') ||
    process.argv[1].endsWith('generate-element-api-entry.js'));

if (isDirectExecution) {
  generateElementApiEntry();
}
